### ISSUE TITLE
Extraction failing for some cases

### ISSUE THREAD

**Issue by koustuvsinha** [annefried/sitent#2]
Hi, I am using this system to extract the situation entity types for a bunch of literary texts. While one group of them could be processed smoothly enough, another group is causing the annotator to fail, leaving no situation type annotation. I am posting the failure start position error : 

```java
Reading arffs from directory: /tmp/tmpb9Fatt/temp/processed_arff_compatible
Exception in thread "Thread-0" java.lang.IllegalArgumentException: A nominal attribute (main_verb_clauseAdverbPred) cannot have duplicate labels (QUOTE).
   at weka.core.NominalAttributeInfo.<init>(NominalAttributeInfo.java:60)
   at weka.core.NominalAttributeInfo.<init>(NominalAttributeInfo.java:60) 
   at weka.core.Attribute.<init>(Attribute.java:271)
   at weka.core.Attribute.<init>(Attribute.java:245)
   at weka.core.Attribute.<init>(Attribute.java:825)       
   at weka.core.converters.ArffLoader$ArffReader.parseAttribute(ArffLoader.java:9$)
   at weka.core.converters.ArffLoader$ArffReader.readHeader(ArffLoader.java:815)
   at weka.core.converters.ArffLoader$ArffReader.<init>(ArffLoader.java:204)
   at weka.core.Instances.<init>(Instances.java:134)
   at sitent.classifiers.Experiment.run(Experiment.java:1403)
```

Can you shed light on this? I think it might be due to some issues with the input files, because your system worked fine with another bunch of text, but I am clueless.

**Comment by annefried** [comment]
Hi, sorry for the late response. This happens when something with the quoting in the Weka input file goes wrong. I have recently fixed some bugs related to this, could you please try again whether it works with your input data now? Thanks!
